- name: Deploy Application
  hosts: raspberrypi
  become: yes
  tasks:
    - name: Set environment variable
      lineinfile:
        path: /etc/environment
        regexp: '^FLASK_BASE_PATH='
        line: "FLASK_BASE_PATH={{ lookup('env', 'FLASK_BASE_PATH') }}"
    - name: zeich mal her
      shell:
        cmd: echo {{ lookup('env', 'FLASK_BASE_PATH') }}
    - name: Deploy Application
      copy:
        src: ../Ambilight_Flask
        dest: /home/luca/
        owner: luca
        group: luca
      