- name: Deploy Application
  hosts: raspberrypi
  become: yes
  tasks:
#    - name: Set environment variable in /etc/environment
#      lineinfile:
#        path: /etc/environment
#        regexp: '^FLASK_BASE_PATH='
#        line: "FLASK_BASE_PATH={{ lookup('env', 'FLASK_BASE_PATH') }}"
#    - name: Set environment variable in ~/.bashrc
#      lineinfile:
#        path: "{{ lookup('env', 'FLASK_BASE_PATH') }}/.bashrc"
#        line: "export FLASK_BASE_PATH={{ lookup('env', 'FLASK_BASE_PATH') }}"
#        create: yes
    - name: Setze FLASK_BASE_PATH in venv/bin/activate
      lineinfile:
        path: "{{ lookup('env', 'FLASK_BASE_PATH') }}/venv/bin/activate"  # Passe den Pfad deines venv an
        line: "export FLASK_BASE_PATH={{ lookup('env', 'FLASK_BASE_PATH') }}"
        create: yes
    - name: Deploy Application
      copy:
        src: ../Ambilight_Flask
        dest: /home/luca/
        owner: luca
        group: luca
      