[all]
raspberrypi ansible_host="{{ lookup('env', 'SERVER_IP') }}" ansible_user="{{ lookup('env', 'SSH_USER') }}" ansible_ssh_pass="{{ lookup('env', 'SSH_PASSWORD') }}" ansible_become_password="{{ lookup('env', 'SSH_PASSWORD') }}" ansible_ssh_common_args='-o ProxyCommand="cloudflared access ssh --hostname %h"'
